title: Thibault Jamet
legend: Photographer - Backend developer
url: //thibaultjamet.github.io
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
